version: "3"

services:
  mariadb-core:
    image: mariadb:latest
    container_name: mariadb-core
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_TCP_PORT= 3308
    ports:
      - 3308:3308

  mariadb-auth:
    image: mariadb:latest
    container_name: mariadb-auth
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_TCP_PORT= 3307
    ports:
      - 3307:3307

  mariadb-localhistory:
    image: mariadb:latest
    container_name: mariadb-localhistory
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=local_order_history
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306

  discovery:
    image: taasnamespace/eurekadiscovery:latest
    container_name: eureka-discovery
    ports:
      - 8083:8083

  auth:
    image: taasnamespace/drink_take_away_auth:3
    container_name: drinktakeaway_auth
    depends_on:
      - mariadb-auth
      - discovery
    ports:
      - 7777:7777
  core:
    image: taasnamespace/drink_take_away_core:4
    container_name: drinktakeaway_core
    depends_on:
      - mariadb-core
      - mariadb-auth
      - discovery
    ports:
      - 1111:1111

  local:
    image: taasnamespace/drink_take_away_local:1
    container_name: drinktakeaway_local
    depends_on:
      - mariadb-core
      - discovery
    ports:
      - 1113:1113

  localhistory:
    image: taasnamespace/drink_take_away_localhistory:3
    container_name: drinktakeaway_localhistory
    depends_on:
      - mariadb-localhistory
      - discovery
    ports:
      - 1112:1112

