apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-volume2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mariadb/core/"