apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-volume1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1.2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mariadb/localhistory/"