apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  type: LoadBalancer
  ports:
  - name: "7777"
    port: 7777
    targetPort: 7777
    nodePort: 30005
  selector:
    io.kompose.service: auth
status:
  loadBalancer: {}
