apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
      - image: taasnamespace/drink_take_away_auth:3
        imagePullPolicy: ""
        name: drinktakeaway-auth
        ports:
        - containerPort: 7777
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
