apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-lh-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.2Gi