apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-auth
  name: mariadb-auth
spec:
  type: ExternalName
  # https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
  externalName: host.docker.internal
  ports:
  - name: "3307"
    port: 3307
    targetPort: 3307
  selector:
    io.kompose.service: mariadb-auth
status:
  loadBalancer: {}
